# # Definitions of tags to detect
#
# ## General remarks
#
# - All length in meters
# - Ellipsis (...) signifies that the previous element can be repeated multiple times.
#
# ## Standalone tag definitions
# ### Remarks
#
# - name is optional
#
# ### Syntax
#
# standalone_tags:
#   [
#     {id: ID, size: SIZE, name: NAME},
#     ...
#   ]
standalone_tags:
  [
  #{id: 0, size: 0.0755, name: "tag_0"},
  #{id: 1, size: 0.0755, name: "tag_1"},
  {id: 2, size: 0.0755, name: "tag_2"}
  #{id: 3, size: 0.0755, name: "tag_3"},
  #{id: 4, size: 0.0755, name: "tag_4"},
  #{id: 5, size: 0.0755, name: "tag_5"}
  ]
# ## Tag bundle definitions
# ### Remarks
#
# - name is optional
# - x, y, z have default values of 0 thus they are optional
# - qw has default value of 1 and qx, qy, qz have default values of 0 thus they are optional
#
# ### Syntax
#
# tag_bundles:
#   [
#     {
#       name: 'CUSTOM_BUNDLE_NAME',
#       layout:
#         [
#           {id: ID, size: SIZE, x: X_POS, y: Y_POS, z: Z_POS, qw: QUAT_W_VAL, qx: QUAT_X_VAL, qy: QUAT_Y_VAL, qz: QUAT_Z_VAL},
#           ...
#         ]
#     },
#     ...
#   ]
######### TODO: correct orientations of markers on each face... thats the most likely cause for jumpyness in output
# tag_bundles:
#   [
# {
# name: 'APRIL_CUBE',
# layout:
# [
# {id: 0, size: 0.31111111, x: 0.0, y: 0.0, z: -0.2, qw: 0.0, qx: -0.7071068, qy: 0.7071068, qz: 0.0},
# {id: 1, size: 0.31111111, x: 0.0, y: 0.2, z: 0.0, qw: -0.5, qx: 0.5, qy: -0.5, qz: -0.5},
# {id: 2, size: 0.31111111, x: 0.0, y: 0.0, z: 0.2, qw: 0.7071068, qx: 0.0, qy: 0.0, qz: 0.7071068},
# {id: 3, size: 0.31111111, x: 0.0, y: -0.2, z: 0.0, qw: 0.0, qx: 0.0, qy: -0.7071068, qz: 0.7071068},
# {id: 4, size: 0.31111111, x: 0.2, y: 0.0, z: 0.0, qw: 0.7071068, qx: 0.0, qy: 0.7071068, qz: 0.0},
# {id: 5, size: 0.31111111, x: -0.2, y: 0.0, z: 0.0, qw: 0.0, qx: -0.7071068, qy: 0.0, qz: 0.7071068}
# ]
# }
#   ]
